spring:
  datasource:
    # 开发环境数据库（可按需修改）
    url: jdbc:mysql://10.189.111.201:2883/track?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root@inetmysql#haiguangOb
    password: roOT123_@#
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
