spring:
  datasource:
    # 开发环境数据库（可按需修改）
    url: jdbc:mysql://101.132.47.124:33306/track?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: linkage@12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql